/* Product catalog + all copy lives here so the page composition stays clean */

const BRL = (n) => "R$ " + n.toFixed(2).replace(".", ",");

const PRODUCTS = [
  {
    id: "gotas-50ml",
    name: "Óleo de Avestruz  Gotas 50ml",
    short: "Uso direto, culinário e em saladas",
    type: "Gotas",
    price: 59.90,
    parcela: 19.97,
    art: "drop",
    img: "assets/product-gotas-50ml.png",
    rating: 4.9,
    reviews: 312,
    details: {
      description: "Extraído a frio da banha do avestruz criado em liberdade no coração do Brasil, nosso Óleo em Gotas é a versão mais versátil da linha Amazon BSB. Rico em Ômegas 3, 6, 7 e 9 e em Vitaminas A e E  nutrientes raros de encontrar juntos em uma única fonte natural. Sabor suave, absorção rápida.",
      benefits: [
        "Fonte completa de Ômegas 3, 6, 7 e 9",
        "Rico em Vitaminas A e E antioxidantes",
        "Uso culinário: saladas, sucos e pratos prontos",
        "Absorção rápida pelo organismo",
        "100% natural, sem glúten e sem aditivos",
      ],
      howToUse: "5 a 10 gotas ao dia, diretamente ou misturadas em sucos, saladas e pratos prontos. Para melhores resultados, mantenha o uso contínuo por pelo menos 60 dias.",
      composition: "Óleo de avestruz (Struthio camelus). Não contém glúten. Conservar em local fresco e seco ao abrigo da luz.",
      volume: "50ml",
    },
  },
  {
    id: "caps-60",
    name: "Óleo de Avestruz  60 Cápsulas",
    short: "500mg por cápsula • 30 dias de uso",
    type: "Cápsulas",
    price: 59.90,
    parcela: 19.97,
    art: "pill",
    img: "assets/product-caps-60.png",
    rating: 4.8,
    reviews: 478,
    details: {
      description: "Praticidade e precisão de dose na mesma cápsula. Cada unidade contém 500mg de Óleo de Avestruz puro  sem sabor, sem odor, fácil de engolir. Ideal para quem quer começar a suplementar com segurança e consistência, com duração de 30 a 60 dias.",
      benefits: [
        "500mg de óleo puro por cápsula",
        "Dosagem padronizada e fácil de controlar",
        "Sem sabor  perfeito para quem não aprecia o sabor do óleo",
        "30 a 60 dias de uso por frasco",
        "Ômegas 3, 6, 7 e 9 + Vitaminas A e E",
      ],
      howToUse: "1 a 2 cápsulas ao dia, preferencialmente com as refeições. Para melhores resultados, mantenha o uso por pelo menos 60 dias.",
      composition: "Óleo de avestruz (Struthio camelus), gelatina bovina, glicerina. Não contém glúten.",
      volume: "60 cápsulas · 500mg por cápsula",
    },
  },
  {
    id: "caps-90",
    name: "Óleo de Avestruz  90 Cápsulas",
    short: "500mg por cápsula • 45 dias de uso",
    type: "Cápsulas",
    price: 79.90,
    parcela: 26.63,
    art: "pill",
    img: "assets/product-caps-90.png",
    rating: 4.9,
    reviews: 612,
    tag: "frete",
    details: {
      description: "Para quem já conhece os benefícios e quer continuidade. Com 90 cápsulas por frasco, você tem de 45 a 90 dias de uso  suficiente para sentir os resultados de forma consistente. Frete grátis incluso e custo por cápsula menor que o frasco de 60.",
      benefits: [
        "90 cápsulas · 45 a 90 dias de uso",
        "Frete grátis em todo o Brasil",
        "Custo por cápsula menor que o frasco de 60un",
        "500mg de óleo puro por cápsula",
        "Ômegas 3, 6, 7 e 9 + Vitaminas A e E",
      ],
      howToUse: "1 a 2 cápsulas ao dia, preferencialmente com as refeições.",
      composition: "Óleo de avestruz (Struthio camelus), gelatina bovina, glicerina. Não contém glúten.",
      volume: "90 cápsulas · 500mg por cápsula",
    },
  },
  {
    id: "kit3-gotas",
    name: "Kit 3x Gotas 50ml",
    short: "Para 3 meses de uso contínuo",
    type: "Kits",
    price: 173.90,
    parcela: 57.97,
    was: 179.70,
    art: "drop",
    img: "assets/product-kit3-gotas.png",
    rating: 5.0,
    reviews: 188,
    tag: "frete",
    details: {
      description: "Três frascos de Óleo de Avestruz em Gotas para 3 meses de uso contínuo. O tempo ideal para sentir os resultados plenos  e ainda sair na frente com frete grátis e economia garantida.",
      benefits: [
        "3 frascos de 50ml",
        "3 meses de suplementação contínua",
        "Frete grátis em todo o Brasil",
        "Economize R$ 5,80 vs. compras avulsas",
        "Uso culinário e direto",
      ],
      howToUse: "5 a 10 gotas ao dia, diretamente ou misturadas em alimentos.",
      composition: "3× Óleo de avestruz (Struthio camelus). Não contém glúten.",
      volume: "3 × 50ml",
    },
  },
  {
    id: "kit3-caps60",
    name: "Kit 3x Cápsulas 60un",
    short: "90 dias de uso • Ômegas 3,6,7 e 9",
    type: "Kits",
    price: 173.90,
    parcela: 57.97,
    was: 179.70,
    art: "pill",
    img: "assets/product-kit3-caps60.png",
    rating: 4.9,
    reviews: 244,
    tag: "frete",
    details: {
      description: "Três frascos de 60 cápsulas para 90 dias de uso contínuo  o tempo ideal para sentir os resultados plenos do Óleo de Avestruz. Frete grátis incluso.",
      benefits: [
        "3 frascos de 60 cápsulas cada",
        "90 dias de suplementação contínua",
        "Frete grátis em todo o Brasil",
        "Economize R$ 5,80 vs. unidades avulsas",
        "500mg de óleo puro por cápsula",
      ],
      howToUse: "1 a 2 cápsulas ao dia, preferencialmente com as refeições.",
      composition: "3× Óleo de avestruz, gelatina bovina, glicerina. Não contém glúten.",
      volume: "3 × 60 cápsulas",
    },
  },
  {
    id: "kit3-caps90",
    name: "Kit 3x Cápsulas 90un",
    short: "135 dias de uso • Mais Vendido",
    type: "Kits",
    price: 231.90,
    parcela: 77.30,
    was: 239.70,
    art: "pill",
    img: "assets/product-kit3-caps90.png",
    rating: 4.9,
    reviews: 521,
    tag: "best",
    details: {
      description: "O kit mais pedido pelos nossos clientes. Três frascos de 90 cápsulas garantem 135 dias de uso contínuo  com brinde surpresa e frete grátis para todo o Brasil.",
      benefits: [
        "3 frascos de 90 cápsulas cada",
        "135 dias de suplementação contínua",
        "Frete grátis + brinde surpresa",
        "Economize R$ 7,80 vs. unidades avulsas",
        "500mg de óleo puro por cápsula",
      ],
      howToUse: "1 a 2 cápsulas ao dia, preferencialmente com as refeições.",
      composition: "3× Óleo de avestruz, gelatina bovina, glicerina. Não contém glúten.",
      volume: "3 × 90 cápsulas",
    },
  },
  {
    id: "kit5-caps60",
    name: "Kit 5x Cápsulas 60un",
    short: "Para toda a família • 150 dias",
    type: "Kits",
    price: 284.90,
    parcela: 94.97,
    was: 299.50,
    art: "pill",
    img: "assets/product-kit5-caps60.png",
    rating: 4.9,
    reviews: 162,
    tag: "value",
    details: {
      description: "Cinco frascos para você, sua família e quem você ama. 150 dias de uso com o maior desconto da linha  ideal para quem já usa e quer garantir o estoque.",
      benefits: [
        "5 frascos de 60 cápsulas cada",
        "150 dias de suplementação contínua",
        "Frete grátis em todo o Brasil",
        "Economize R$ 14,60 vs. unidades avulsas",
        "Ideal para toda a família",
      ],
      howToUse: "1 a 2 cápsulas ao dia, preferencialmente com as refeições.",
      composition: "5× Óleo de avestruz, gelatina bovina, glicerina. Não contém glúten.",
      volume: "5 × 60 cápsulas",
    },
  },
  {
    id: "kit5-gotas",
    name: "Kit 5x Gotas 50ml",
    short: "Versátil • culinário e direto",
    type: "Kits",
    price: 284.90,
    parcela: 94.97,
    was: 299.50,
    art: "drop",
    img: "assets/product-kit5-gotas.png",
    rating: 4.8,
    reviews: 98,
    tag: "value",
    details: {
      description: "Cinco frascos de gotas para uso contínuo e culinário. O kit mais econômico da linha para quem prefere a versão líquida e quer garantir o estoque por meses.",
      benefits: [
        "5 frascos de 50ml",
        "5 meses de suplementação contínua",
        "Frete grátis em todo o Brasil",
        "Economize R$ 14,60 vs. compras avulsas",
        "Versátil: culinário e uso direto",
      ],
      howToUse: "5 a 10 gotas ao dia, diretamente ou misturadas em alimentos.",
      composition: "5× Óleo de avestruz (Struthio camelus). Não contém glúten.",
      volume: "5 × 50ml",
    },
  },
  {
    id: "kit5-caps90",
    name: "Kit 5x Cápsulas 90un",
    short: "Maior economia • 225 dias de uso",
    type: "Kits",
    price: 357.90,
    parcela: 119.30,
    was: 399.50,
    art: "pill",
    img: "assets/product-kit5-caps90.png",
    rating: 5.0,
    reviews: 134,
    tag: "value",
    details: {
      description: "O maior kit da linha Amazon BSB  225 dias de uso contínuo com o melhor preço por cápsula. Para quem levou a sério e quer garantir resultados duradouros.",
      benefits: [
        "5 frascos de 90 cápsulas cada",
        "225 dias de suplementação contínua",
        "Frete grátis em todo o Brasil",
        "Economize R$ 41,60 vs. unidades avulsas",
        "Melhor custo por cápsula da linha",
      ],
      howToUse: "1 a 2 cápsulas ao dia, preferencialmente com as refeições.",
      composition: "5× Óleo de avestruz, gelatina bovina, glicerina. Não contém glúten.",
      volume: "5 × 90 cápsulas",
    },
  },
];

const UPSELL_MAP = {
  "gotas-50ml": {
    kitId: "kit3-gotas",
    savings: 5.80,
    headline: "Leve o Kit 3x e ganhe frete grátis!",
    sub: "3 meses de uso contínuo. Economize R$ 5,80 e receba sem frete.",
  },
  "caps-60": {
    kitId: "kit3-caps60",
    savings: 5.80,
    headline: "Upgrade para o Kit 3x e economize!",
    sub: "90 dias de uso com frete grátis incluso. Economize R$ 5,80.",
  },
  "caps-90": {
    kitId: "kit3-caps90",
    savings: 7.80,
    headline: "O kit mais pedido pelos nossos clientes.",
    sub: "135 dias + brinde surpresa + frete grátis. Economize R$ 7,80.",
  },
};

const COUPON = { code: "PRIMEIRACOMPRA10", discount: 10 };

const FAQS = [
  {
    q: "Qual a diferença entre as gotas e as cápsulas?",
    a: "As gotas são líquidas e podem ser usadas diretamente, em saladas, sucos ou pratos prontos  perfeitas para quem gosta de incorporar ao dia a dia culinário. As cápsulas (500mg) são práticas para tomar como suplemento, ideais para quem busca rapidez e dosagem padronizada.",
  },
  {
    q: "Como devo tomar o Óleo de Avestruz?",
    a: "Recomendamos seguir a indicação do rótulo: 1 a 2 cápsulas ao dia preferencialmente com as refeições, ou de 5 a 10 gotas diárias. Para melhores resultados, mantenha o uso contínuo por pelo menos 60 dias.",
  },
  {
    q: "O produto é livre de glúten?",
    a: "Sim. O Óleo de Avestruz Amazon BSB é 100% natural e não contém glúten, sendo seguro para pessoas com doença celíaca ou sensibilidade ao glúten.",
  },
  {
    q: "Qual produto é mais indicado para começar?",
    a: "Para quem está começando, recomendamos as cápsulas de 60 unidades  duram cerca de 30 a 60 dias e permitem sentir os efeitos com investimento menor. Quem busca economia, o Kit 3x 90 cápsulas é o mais pedido pelos nossos clientes.",
  },
  {
    q: "Qual o prazo de entrega?",
    a: "Enviamos em até 1 dia útil após a confirmação do pagamento. O prazo médio de entrega é de 3 a 7 dias úteis para a maioria das capitais e de 5 a 12 dias úteis para o interior  entregamos em todo o Brasil.",
  },
  {
    q: "Como funciona o frete grátis?",
    a: "O frete é gratuito automaticamente em todas as compras acima de R$ 150,00 para todo o Brasil. Abaixo desse valor, o valor do frete é calculado pelo CEP no checkout.",
  },
  {
    q: "Quais são as formas de pagamento?",
    a: "Aceitamos cartão de crédito (em até 3x sem juros), Pix, boleto bancário e PayPal. O pagamento é processado em ambiente seguro com criptografia SSL.",
  },
  {
    q: "Posso comprar pelo WhatsApp?",
    a: "Sim! Nossa equipe atende pelo WhatsApp (61) 99954-5567 de segunda a sábado. Tiramos suas dúvidas, ajudamos a escolher o produto ideal e finalizamos a venda pelo próprio canal.",
  },
];

const TESTIMONIALS = [
  {
    name: "Marina Souza",
    city: "Brasília, DF",
    initials: "MS",
    cls: "a1",
    rating: 5,
    text: "Comecei com as cápsulas de 60 e em 3 semanas já notei mais disposição no trabalho. Pacote bem embalado e chegou rápido em casa.",
  },
  {
    name: "Carlos Ribeiro",
    city: "Goiânia, GO",
    initials: "CR",
    cls: "a2",
    rating: 5,
    text: "Comprei o kit 3x para mim e para minha esposa. A pele dela melhorou muito  está acompanhando os Ômegas com o nutricionista.",
  },
  {
    name: "Patrícia Lima",
    city: "São Paulo, SP",
    initials: "PL",
    cls: "a3",
    rating: 5,
    text: "Uso as gotas direto na salada todos os dias. Sabor neutro e prático. Atendimento pelo WhatsApp foi excelente, tirou todas as dúvidas.",
  },
];

window.PRODUCTS = PRODUCTS;
window.FAQS = FAQS;
window.TESTIMONIALS = TESTIMONIALS;
window.BRL = BRL;
window.UPSELL_MAP = UPSELL_MAP;
window.COUPON = COUPON;
