/* Product catalog + all copy lives here so the page composition stays clean */

const BRL = (n) => "R$ " + n.toFixed(2).replace(".", ",");

const PRODUCTS = [
  {
    id: "gotas-50ml",
    name: "Óleo de Avestruz — Gotas 50ml",
    short: "Uso direto, culinário e em saladas",
    type: "Gotas",
    price: 75.90,
    parcela: 25.30,
    art: "drop",
    img: "assets/product-gotas-50ml.png",
    rating: 4.9,
    reviews: 312,
  },
  {
    id: "caps-60",
    name: "Óleo de Avestruz — 60 Cápsulas",
    short: "500mg por cápsula • 30 dias de uso",
    type: "Cápsulas",
    price: 75.90,
    parcela: 25.30,
    art: "pill",
    img: "assets/product-caps-60.png",
    rating: 4.8,
    reviews: 478,
  },
  {
    id: "caps-90",
    name: "Óleo de Avestruz — 90 Cápsulas",
    short: "500mg por cápsula • 45 dias de uso",
    type: "Cápsulas",
    price: 94.90,
    parcela: 31.63,
    art: "pill",
    img: "assets/product-caps-90.png",
    rating: 4.9,
    reviews: 612,
    tag: "frete",
  },
  {
    id: "kit3-gotas",
    name: "Kit 3x Gotas 50ml",
    short: "Para 3 meses de uso contínuo",
    type: "Kits",
    price: 219.90,
    parcela: 73.30,
    was: 227.70,
    art: "drop",
    img: "assets/product-kit3-gotas.png",
    rating: 5.0,
    reviews: 188,
    tag: "frete",
  },
  {
    id: "kit3-caps60",
    name: "Kit 3x Cápsulas 60un",
    short: "90 dias de uso • Ômegas 3,6,7 e 9",
    type: "Kits",
    price: 219.90,
    parcela: 73.30,
    was: 227.70,
    art: "pill",
    img: "assets/product-kit3-caps60.png",
    rating: 4.9,
    reviews: 244,
    tag: "frete",
  },
  {
    id: "kit3-caps90",
    name: "Kit 3x Cápsulas 90un",
    short: "135 dias de uso • Mais Vendido",
    type: "Kits",
    price: 274.90,
    parcela: 91.63,
    was: 284.70,
    art: "pill",
    img: "assets/product-kit3-caps90.png",
    rating: 4.9,
    reviews: 521,
    tag: "best",
  },
  {
    id: "kit5-caps60",
    name: "Kit 5x Cápsulas 60un",
    short: "Para toda a família • 150 dias",
    type: "Kits",
    price: 359.90,
    parcela: 119.97,
    was: 379.50,
    art: "pill",
    img: "assets/product-kit5-caps60.png",
    rating: 4.9,
    reviews: 162,
    tag: "value",
  },
  {
    id: "kit5-gotas",
    name: "Kit 5x Gotas 50ml",
    short: "Versátil • culinário e direto",
    type: "Kits",
    price: 359.90,
    parcela: 119.97,
    was: 379.50,
    art: "drop",
    img: "assets/product-kit5-gotas.png",
    rating: 4.8,
    reviews: 98,
    tag: "value",
  },
  {
    id: "kit5-caps90",
    name: "Kit 5x Cápsulas 90un",
    short: "Maior economia • 225 dias de uso",
    type: "Kits",
    price: 424.90,
    parcela: 141.63,
    was: 474.50,
    art: "pill",
    img: "assets/product-kit5-caps90.png",
    rating: 5.0,
    reviews: 134,
    tag: "value",
  },
];

const FAQS = [
  {
    q: "Qual a diferença entre as gotas e as cápsulas?",
    a: "As gotas são líquidas e podem ser usadas diretamente, em saladas, sucos ou pratos prontos — perfeitas para quem gosta de incorporar ao dia a dia culinário. As cápsulas (500mg) são práticas para tomar como suplemento, ideais para quem busca rapidez e dosagem padronizada.",
  },
  {
    q: "Como devo tomar o Óleo de Avestruz?",
    a: "Recomendamos seguir a indicação do rótulo: 1 a 2 cápsulas ao dia preferencialmente com as refeições, ou de 5 a 10 gotas diárias. Para melhores resultados, mantenha o uso contínuo por pelo menos 60 dias.",
  },
  {
    q: "O produto é livre de glúten?",
    a: "Sim. O Óleo de Avestruz Amazon BSB é 100% natural e não contém glúten, sendo seguro para pessoas com doença celíaca ou sensibilidade ao glúten.",
  },
  {
    q: "Qual produto é mais indicado para começar?",
    a: "Para quem está começando, recomendamos as cápsulas de 60 unidades — duram cerca de 30 a 60 dias e permitem sentir os efeitos com investimento menor. Quem busca economia, o Kit 3x 90 cápsulas é o mais pedido pelos nossos clientes.",
  },
  {
    q: "Qual o prazo de entrega?",
    a: "Enviamos em até 1 dia útil após a confirmação do pagamento. O prazo médio de entrega é de 3 a 7 dias úteis para a maioria das capitais e de 5 a 12 dias úteis para o interior — entregamos em todo o Brasil.",
  },
  {
    q: "Como funciona o frete grátis?",
    a: "O frete é gratuito automaticamente em todas as compras acima de R$ 150,00 para todo o Brasil. Abaixo desse valor, o valor do frete é calculado pelo CEP no checkout.",
  },
  {
    q: "Quais são as formas de pagamento?",
    a: "Aceitamos cartão de crédito (em até 3x sem juros), Pix, boleto bancário e PayPal. O pagamento é processado em ambiente seguro com criptografia SSL.",
  },
  {
    q: "Posso comprar pelo WhatsApp?",
    a: "Sim! Nossa equipe atende pelo WhatsApp (61) 99954-5567 de segunda a sábado. Tiramos suas dúvidas, ajudamos a escolher o produto ideal e finalizamos a venda pelo próprio canal.",
  },
];

const TESTIMONIALS = [
  {
    name: "Marina Souza",
    city: "Brasília, DF",
    initials: "MS",
    cls: "a1",
    rating: 5,
    text: "Comecei com as cápsulas de 60 e em 3 semanas já notei mais disposição no trabalho. Pacote bem embalado e chegou rápido em casa.",
  },
  {
    name: "Carlos Ribeiro",
    city: "Goiânia, GO",
    initials: "CR",
    cls: "a2",
    rating: 5,
    text: "Comprei o kit 3x para mim e para minha esposa. A pele dela melhorou muito — está acompanhando os Ômegas com o nutricionista.",
  },
  {
    name: "Patrícia Lima",
    city: "São Paulo, SP",
    initials: "PL",
    cls: "a3",
    rating: 5,
    text: "Uso as gotas direto na salada todos os dias. Sabor neutro e prático. Atendimento pelo WhatsApp foi excelente, tirou todas as dúvidas.",
  },
];

window.PRODUCTS = PRODUCTS;
window.FAQS = FAQS;
window.TESTIMONIALS = TESTIMONIALS;
window.BRL = BRL;
